environments:
- name: dev
  iss: https://dev.com
  tokens:
  - token_type: access
    oauth_flow: ClientCredentialsFlow
    client_credentials:
      client_id: client_id
      client_secret: client_secret
    user_password: null
- name: syst
  iss: https://dev.com
  tokens: []
